
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},d),g=(a,b)=>{throw b;},p="";"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src);p=0!==p.indexOf("blob:")?p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ba=d.print||console.log.bind(console),q=d.printErr||console.warn.bind(console);Object.assign(d,aa);aa=null;d.quit&&(g=d.quit);var r;d.wasmBinary&&(r=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;
"object"!=typeof WebAssembly&&t("no native wasm support detected");var ca,u=!1,da="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function v(a){if(a){for(var b=w,c=a+NaN,e=a;b[e]&&!(e>=c);)++e;if(16<e-a&&b.buffer&&da)a=da.decode(b.subarray(a,e));else{for(c="";a<e;){var f=b[a++];if(f&128){var h=b[a++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var k=b[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|b[a++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}a=c}}else a="";return a}
function x(a,b,c){var e=w;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(b>=c)break;e[b++]=h}else{if(2047>=h){if(b+1>=c)break;e[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;e[b++]=224|h>>12}else{if(b+3>=c)break;e[b++]=240|h>>18;e[b++]=128|h>>12&63}e[b++]=128|h>>6&63}e[b++]=128|h&63}}e[b]=0}}
function y(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}var w,B,ea,fa,ia,ja=[],ka=[],la=[],ma=[];function na(){var a=d.preRun.shift();ja.unshift(a)}var C=0,oa=null,E=null;function t(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";q(a);u=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function pa(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="index.wasm";if(!pa()){var qa=F;F=d.locateFile?d.locateFile(qa,p):p+qa}function ra(){var a=F;try{if(a==F&&r)return new Uint8Array(r);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function sa(){return r||"function"!=typeof fetch?Promise.resolve().then(function(){return ra()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return ra()})}
var ta={4020:()=>window.innerHeight,4051:()=>window.innerWidth,4081:()=>window.outerHeight,4112:()=>window.outerWidth,4142:()=>{window.blur()},4161:a=>{document.getElementById(v(a))||document.body.appendChild(document.createElement("canvas")).setAttribute("id",v(a))},4311:a=>document.getElementById(v(a)).width,4371:a=>document.getElementById(v(a)).height,4432:(a,b)=>{document.getElementById(v(a)).height=b},4491:(a,b)=>{document.getElementById(v(a)).width=b},4549:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").clearRect(b,
c,e,f)},4639:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").fillRect(b,c,e,f)},4728:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").strokeRect(b,c,e,f)},4819:(a,b,c,e)=>{document.getElementById(v(a)).getContext("2d").fillText(v(b),c,e)},4918:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").fillText(v(b),c,e,f)},5021:(a,b,c,e)=>{document.getElementById(v(a)).getContext("2d").strokeText(v(b),c,e)},5122:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").strokeText(v(b),
c,e,f)},5227:(a,b)=>{document.getElementById(v(a)).getContext("2d").lineWidth=b},5308:a=>document.getElementById(v(a)).getContext("2d").lineWidth,5389:(a,b)=>{document.getElementById(v(a)).getContext("2d").lineCap=v(b)},5480:a=>{a=document.getElementById(v(a)).getContext("2d").lineCap;var b=y(a)+1,c=G(b);x(a,c,b);return c},5690:(a,b)=>{document.getElementById(v(a)).getContext("2d").lineJoin=v(b)},5782:a=>{a=document.getElementById(v(a)).getContext("2d").lineJoin;var b=y(a)+1,c=G(b);x(a,c,b);return c},
5993:(a,b)=>{document.getElementById(v(a)).getContext("2d").font=v(b)},6081:a=>{a=document.getElementById(v(a)).getContext("2d").font;var b=y(a)+1,c=G(b);x(a,c,b);return c},6288:(a,b)=>{document.getElementById(v(a)).getContext("2d").textAlign=v(b)},6381:a=>{a=document.getElementById(v(a)).getContext("2d").textAlign;var b=y(a)+1,c=G(b);x(a,c,b);return c},6593:(a,b)=>{document.getElementById(v(a)).getContext("2d").fillStyle=v(b)},6686:a=>{a=document.getElementById(v(a)).getContext("2d").fillStyle;var b=
y(a)+1,c=G(b);x(a,c,b);return c},6898:(a,b)=>{document.getElementById(v(a)).getContext("2d").strokeStyle=v(b)},6993:a=>{a=document.getElementById(v(a)).getContext("2d").strokeStyle;var b=y(a)+1,c=G(b);x(a,c,b);return c},7207:a=>{document.getElementById(v(a)).getContext("2d").beginPath()},7283:a=>{document.getElementById(v(a)).getContext("2d").closePath()},7359:(a,b,c)=>{document.getElementById(v(a)).getContext("2d").moveTo(b,c)},7438:(a,b,c)=>{document.getElementById(v(a)).getContext("2d").lineTo(b,
c)},7517:(a,b,c,e,f,h,k)=>{document.getElementById(v(a)).getContext("2d").bezierCurveTo(b,c,e,f,h,k)},7619:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").quadraticCurveTo(b,c,e,f)},7716:(a,b,c,e,f,h)=>{document.getElementById(v(a)).getContext("2d").arc(b,c,e,f,h)},7804:(a,b,c,e,f,h)=>{document.getElementById(v(a)).getContext("2d").arcTo(b,c,e,f,h)},7894:(a,b,c,e,f,h,k,m)=>{document.getElementById(v(a)).getContext("2d").ellipse(b,c,e,f,h,k,m)},7994:(a,b,c,e,f)=>{document.getElementById(v(a)).getContext("2d").rect(b,
c,e,f)},8079:a=>{document.getElementById(v(a)).getContext("2d").fill()},8150:a=>{document.getElementById(v(a)).getContext("2d").stroke()},8223:a=>{document.getElementById(v(a)).getContext("2d").clip()},8294:(a,b,c)=>document.getElementById(v(a)).getContext("2d").isPointInPath(b,c),8387:(a,b,c)=>document.getElementById(v(a)).getContext("2d").isPointInStroke(b,c),8482:(a,b)=>{document.getElementById(v(a)).getContext("2d").rotate(b)},8557:(a,b,c)=>{document.getElementById(v(a)).getContext("2d").scale(b,
c)},8635:(a,b,c)=>{document.getElementById(v(a)).getContext("2d").translate(b,c)},8717:(a,b,c,e,f,h,k)=>{document.getElementById(v(a)).getContext("2d").transform(b,c,e,f,h,k)},8815:(a,b,c,e,f,h,k)=>{document.getElementById(v(a)).getContext("2d").setTransform(b,c,e,f,h,k)},8916:a=>{document.getElementById(v(a)).getContext("2d").resetTransform()},8997:(a,b)=>{document.getElementById(v(a)).getContext("2d").globalAlpha=b},9078:a=>document.getElementById(v(a)).getContext("2d").globalAlpha,9161:(a,b)=>
{document.getElementById(v(a)).getContext("2d").globalCompositeOperation=b},9255:a=>{a=document.getElementById(v(a)).getContext("2d").globalCompositeOperation;var b=y(a)+1,c=G(b);x(a,c,b);return c},9482:a=>{document.getElementById(v(a)).getContext("2d").save()},9553:a=>{document.getElementById(v(a)).getContext("2d").restore()}};function ua(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function H(a){for(;0<a.length;)a.shift()(d)}
function va(a){a instanceof ua||"unwind"==a||g(1,a)}var wa=[];function xa(a,b,c){wa.length=0;var e;for(c>>=2;e=w[b++];)c+=105!=e&c,wa.push(105==e?B[c]:fa[c++>>1]),++c;return ta[a].apply(null,wa)}function ya(a){if(!u)try{a()}catch(b){va(b)}}function za(a){setTimeout(function(){ya(a)},1E4)}function Aa(a){I||(I={});I[a]||(I[a]=1,q(a))}var I,Ba=!1,J=null,K=0,L=null,Ca=0,M=0,O=0,Da=0,Ea=[],Fa={},P,Ga,Q,R=!1,Ha=!1,Ia=[];
function Ja(){function a(){Ha=document.pointerLockElement===d.canvas||document.mozPointerLockElement===d.canvas||document.webkitPointerLockElement===d.canvas||document.msPointerLockElement===d.canvas}d.preloadPlugins||(d.preloadPlugins=[]);if(!Ka){Ka=!0;try{S=!0}catch(c){S=!1,q("warning: no blob constructor, cannot create blobs with mimetypes")}La="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:S?null:q("warning: no BlobBuilder");T="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;d.o||"undefined"!=typeof T||(q("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),d.o=!0);d.preloadPlugins.push({canHandle:function(c){return!d.o&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,e,f,h){var k=null;if(S)try{k=new Blob([c],{type:Ma(e)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Ma(e)}))}catch(n){Aa("Blob constructor present but fails: "+
n+"; falling back to blob builder")}k||(k=new La,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=T.createObjectURL(k),l=new Image;l.onload=()=>{l.complete||t("Image "+e+" could not be decoded");var n=document.createElement("canvas");n.width=l.width;n.height=l.height;n.getContext("2d").drawImage(l,0,0);T.revokeObjectURL(m);f&&f(c)};l.onerror=()=>{ba("Image "+m+" could not be decoded");h&&h()};l.src=m}});d.preloadPlugins.push({canHandle:function(c){return!d.J&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,e,f,h){function k(){l||(l=!0,f&&f(c))}function m(){l||(l=!0,new Audio,h&&h())}var l=!1;if(S){try{var n=new Blob([c],{type:Ma(e)})}catch(z){return m()}n=T.createObjectURL(n);var A=new Audio;A.addEventListener("canplaythrough",function(){k(A)},!1);A.onerror=function(){if(!l){q("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var z="",N=0,D=0,ha=0;ha<c.length;ha++)for(N=N<<8|c[ha],D+=8;6<=D;){var Va=N>>D-6&63;D-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Va]}2==
D?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(N&3)<<4],z+="=="):4==D&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(N&15)<<2],z+="=");A.src="data:audio/x-"+e.substr(-3)+";base64,"+z;k(A)}};A.src=n;za(function(){k(A)})}else return m()}});var b=d.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),d.elementPointerLock&&b.addEventListener("click",function(c){!Ha&&d.canvas.requestPointerLock&&(d.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Na(a,b,c,e){if(b&&d.m&&a==d.canvas)return d.m;var f;if(b){var h={antialias:!1,alpha:!1,H:1};if(e)for(var k in e)h[k]=e[k];if("undefined"!=typeof GL&&(f=GL.D(a,h)))var m=GL.getContext(f).A}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof GLctx||t("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),d.m=m,b&&GL.I(f),d.K=b,Ia.forEach(function(l){l()}),Ja());return m}var Oa=!1,U=void 0,V=void 0;
function Pa(a,b){function c(){R=!1;var h=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(e.exitFullscreen=Qa,U&&e.requestPointerLock(),R=!0,V?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=ea[SDL.screen>>2]|8388608),W(d.canvas),Ra()):W(e)):(h.parentNode.insertBefore(e,h),h.parentNode.removeChild(h),V?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=ea[SDL.screen>>2]&-8388609),
W(d.canvas),Ra()):W(e));if(d.onFullScreen)d.onFullScreen(R);if(d.onFullscreen)d.onFullscreen(R)}U=a;V=b;"undefined"==typeof U&&(U=!0);"undefined"==typeof V&&(V=!1);var e=d.canvas;Oa||(Oa=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Qa(){if(!R)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var X=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===X)X=b+1E3/60;else for(;b+2>=X;)X+=1E3/60;setTimeout(a,Math.max(X-b,0))}}
function Ma(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ta=[];function Ra(){var a=d.canvas;Ta.forEach(function(b){b(a.width,a.height)})}
function W(a,b,c){b&&c?(a.v=b,a.s=c):(b=a.v,c=a.s);var e=b,f=c;d.forcedAspectRatio&&0<d.forcedAspectRatio&&(e/f<d.forcedAspectRatio?e=Math.round(f*d.forcedAspectRatio):f=Math.round(e/d.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/e,screen.height/f);e=Math.round(e*h);f=Math.round(f*h)}V?
(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||f!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ka,S,La,T;
function Ua(a,b){M=a;O=b;if(L)if(Ba||(Ba=!0),0==a)J=function(){var e=Math.max(0,Ga+b-Wa())|0;setTimeout(Q,e)};else if(1==a)J=function(){Sa(Q)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",function(e){if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),c.shift()()},!0);setImmediate=function(e){c.push(e);postMessage("setimmediate","*")}}J=function(){setImmediate(Q)}}}var Wa;Wa=()=>performance.now();
function Xa(a,b,c,e,f){!L||t("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");L=a;Ca=e;var h=K;Ba=!1;Q=function(){if(!u)if(0<Ea.length){var k=Date.now(),m=Ea.shift();m.G(m.B);if(P){var l=P,n=0==l%1?l-1:Math.floor(l);P=m.C?n:(8*l+(n+.5))/9}ba('main loop blocker "'+m.name+'" took '+(Date.now()-k)+" ms");d.setStatus&&(k=d.statusMessage||"Please wait...",m=P,l=
Fa.F,m?m<l?d.setStatus(k+" ("+(l-m)+"/"+l+")"):d.setStatus(k):d.setStatus(""));h<K||setTimeout(Q,0)}else h<K||(Da=Da+1|0,1==M&&1<O&&0!=Da%O?J():(0==M&&(Ga=Wa()),u||d.preMainLoop&&!1===d.preMainLoop()||(ya(a),d.postMainLoop&&d.postMainLoop()),h<K||("object"==typeof SDL&&SDL.audio&&SDL.audio.u&&SDL.audio.u(),J())))};f||(b&&0<b?Ua(0,1E3/b):Ua(1,1),J());if(c)throw"unwind";}var Y=[];d.requestFullscreen=function(a,b){Pa(a,b)};d.requestAnimationFrame=function(a){Sa(a)};
d.setCanvasSize=function(a,b,c){W(d.canvas,a,b);c||Ra()};d.pauseMainLoop=function(){J=null;K++};d.resumeMainLoop=function(){K++;var a=M,b=O,c=L;L=null;Xa(c,0,!1,Ca,!0);Ua(a,b);J()};d.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};d.createContext=function(a,b,c,e){return Na(a,b,c,e)};
var Ya={f:function(){return Date.now()},c:xa,a:xa,b:function(a){console.log(v(a))},e:function(a,b,c){w.copyWithin(a,b,b+c)},d:function(){t("OOM")},g:function(a,b,c){var e=Y[a];e||(a>=Y.length&&(Y.length=a+1),Y[a]=e=ia.get(a));Xa(e,b,c)}};
(function(){function a(f){d.asm=f.exports;ca=d.asm.h;f=ca.buffer;d.HEAP8=new Int8Array(f);d.HEAP16=new Int16Array(f);d.HEAP32=B=new Int32Array(f);d.HEAPU8=w=new Uint8Array(f);d.HEAPU16=new Uint16Array(f);d.HEAPU32=ea=new Uint32Array(f);d.HEAPF32=new Float32Array(f);d.HEAPF64=fa=new Float64Array(f);ia=d.asm.k;ka.unshift(d.asm.i);C--;d.monitorRunDependencies&&d.monitorRunDependencies(C);0==C&&(null!==oa&&(clearInterval(oa),oa=null),E&&(f=E,E=null,f()))}function b(f){a(f.instance)}function c(f){return sa().then(function(h){return WebAssembly.instantiate(h,
e)}).then(function(h){return h}).then(f,function(h){q("failed to asynchronously prepare wasm: "+h);t(h)})}var e={a:Ya};C++;d.monitorRunDependencies&&d.monitorRunDependencies(C);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return q("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return r||"function"!=typeof WebAssembly.instantiateStreaming||pa()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(b,function(h){q("wasm streaming compile failed: "+h);q("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.i).apply(null,arguments)};var G=d._malloc=function(){return(G=d._malloc=d.asm.j).apply(null,arguments)};d._main=function(){return(d._main=d.asm.l).apply(null,arguments)};var Z;E=function Za(){Z||$a();Z||(E=Za)};
function $a(){function a(){if(!Z&&(Z=!0,d.calledRun=!0,!u)){H(ka);H(la);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(ab){var b=d._main;try{var c=b(0,0);if(!noExitRuntime){if(d.onExit)d.onExit(c);u=!0}g(c,new ua(c))}catch(e){va(e)}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=d.postRun.shift(),ma.unshift(b);H(ma)}}if(!(0<C)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)na();H(ja);0<C||(d.setStatus?
(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var ab=!0;d.noInitialRun&&(ab=!1);$a();
